version: '3'

services:
  postgres:
    image: postgres:15
    container_name: gymsaas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gymsaaspass123
      POSTGRES_DB: gymsaas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: